Category.delete_all
Category.create( id: 1,  name: '動物' )
Category.create( id: 2,  name: '食べ物' )
Category.create( id: 3,  name: '乗り物' )

ImageQuiz.delete_all
ImageQuiz.create( id: 1, category_id: 1,  image: 'images/1.png', answer: 'いぬ' )
ImageQuiz.create( id: 2, category_id: 1,  image: 'images/2.png', answer: 'ねこ' )
ImageQuiz.create( id: 3, category_id: 1,  image: 'images/3.png', answer: 'さる' )
ImageQuiz.create( id: 4, category_id: 1,  image: 'images/4.png', answer: 'きりん' )
ImageQuiz.create( id: 5, category_id: 1,  image: 'images/5.png', answer: 'ぶた' )
ImageQuiz.create( id: 6, category_id: 1,  image: 'images/6.png', answer: 'へび' )
ImageQuiz.create( id: 7, category_id: 1,  image: 'images/7.png', answer: 'いのしし' )
ImageQuiz.create( id: 8, category_id: 1,  image: 'images/8.png', answer: 'うさぎ' )
ImageQuiz.create( id: 9, category_id: 1,  image: 'images/9.png', answer: 'ぞう' )
ImageQuiz.create( id: 10, category_id: 1,  image: 'images/10.png', answer: 'しか' )
ImageQuiz.create( id: 11, category_id: 1,  image: 'images/11.png', answer: 'ぺんぎん' )
ImageQuiz.create( id: 12, category_id: 1,  image: 'images/12.png', answer: 'らいおん' )
ImageQuiz.create( id: 13, category_id: 1,  image: 'images/13.png', answer: 'かえる' )
ImageQuiz.create( id: 14, category_id: 1,  image: 'images/14.png', answer: 'ぱんだ' )
ImageQuiz.create( id: 15, category_id: 1,  image: 'images/15.png', answer: 'うま' )
ImageQuiz.create( id: 16, category_id: 1,  image: 'images/16.png', answer: 'うし' )
ImageQuiz.create( id: 17, category_id: 1,  image: 'images/17.png', answer: 'かめ' )
ImageQuiz.create( id: 18, category_id: 1,  image: 'images/18.png', answer: 'らくだ' )
ImageQuiz.create( id: 19, category_id: 1,  image: 'images/19.png', answer: 'かば' )
ImageQuiz.create( id: 20, category_id: 1,  image: 'images/20.png', answer: 'こあら' )
ImageQuiz.create( id: 21, category_id: 1,  image: 'images/21.png', answer: 'しまうま' )
ImageQuiz.create( id: 22, category_id: 1,  image: 'images/22.png', answer: 'きつね' )
ImageQuiz.create( id: 23, category_id: 1,  image: 'images/23.png', answer: 'らいおん' )
ImageQuiz.create( id: 24, category_id: 1,  image: 'images/24.png', answer: 'とら' )



ImageQuiz.create( id: 100, category_id: 2,  image: 'images/100.png', answer: 'りんご' )
ImageQuiz.create( id: 101, category_id: 2,  image: 'images/101.png', answer: 'ぶどう' )
ImageQuiz.create( id: 102, category_id: 2,  image: 'images/102.png', answer: 'ねぎ' )
ImageQuiz.create( id: 103, category_id: 2,  image: 'images/103.png', answer: 'すいか' )
ImageQuiz.create( id: 104, category_id: 2,  image: 'images/104.png', answer: 'とまと' )
ImageQuiz.create( id: 105, category_id: 2,  image: 'images/105.png', answer: 'だいこん' )
ImageQuiz.create( id: 106, category_id: 2,  image: 'images/106.png', answer: 'なすび' )
ImageQuiz.create( id: 107, category_id: 2,  image: 'images/107.png', answer: 'きゅうり' )
ImageQuiz.create( id: 108, category_id: 2,  image: 'images/108.png', answer: 'たまご' )
ImageQuiz.create( id: 109, category_id: 2,  image: 'images/109.png', answer: 'れもん' )
ImageQuiz.create( id: 110, category_id: 2,  image: 'images/110.png', answer: 'とうふ' )
ImageQuiz.create( id: 111, category_id: 2,  image: 'images/111.png', answer: 'かぼちゃ' )
ImageQuiz.create( id: 112, category_id: 2,  image: 'images/112.png', answer: 'たけのこ' )
ImageQuiz.create( id: 113, category_id: 2,  image: 'images/113.png', answer: 'ぴーまん' )
ImageQuiz.create( id: 114, category_id: 2,  image: 'images/114.png', answer: 'たまねぎ' )
ImageQuiz.create( id: 115, category_id: 2,  image: 'images/115.png', answer: 'はくさい' )
ImageQuiz.create( id: 116, category_id: 2,  image: 'images/116.png', answer: 'いちご' )
ImageQuiz.create( id: 117, category_id: 2,  image: 'images/117.png', answer: 'めろん' )
ImageQuiz.create( id: 118, category_id: 2,  image: 'images/118.png', answer: 'ぶろっこりー' )
ImageQuiz.create( id: 119, category_id: 2,  image: 'images/119.png', answer: 'ばなな' )
ImageQuiz.create( id: 120, category_id: 2,  image: 'images/120.png', answer: 'だんご' )
ImageQuiz.create( id: 121, category_id: 2,  image: 'images/121.png', answer: 'あいすくりーむ' )
ImageQuiz.create( id: 122, category_id: 2,  image: 'images/122.png', answer: 'ぷりん' )


ImageQuiz.create( id: 200, category_id: 3,  image: 'images/200.png', answer: 'ひこうき' )
ImageQuiz.create( id: 201, category_id: 3,  image: 'images/201.png', answer: 'くるま' )
ImageQuiz.create( id: 202, category_id: 3,  image: 'images/202.png', answer: 'きゅうきゅうしゃ' )
ImageQuiz.create( id: 203, category_id: 3,  image: 'images/203.png', answer: 'ばす' )
ImageQuiz.create( id: 204, category_id: 3,  image: 'images/204.png', answer: 'ふね' )
ImageQuiz.create( id: 205, category_id: 3,  image: 'images/205.png', answer: 'ぱとかー' )
ImageQuiz.create( id: 206, category_id: 3,  image: 'images/206.png', answer: 'しょうぼうしゃ' )
ImageQuiz.create( id: 207, category_id: 3,  image: 'images/207.png', answer: 'へりこぷたー' )
ImageQuiz.create( id: 208, category_id: 3,  image: 'images/208.png', answer: 'じてんしゃ' )
ImageQuiz.create( id: 209, category_id: 3,  image: 'images/209.png', answer: 'ばいく' )
ImageQuiz.create( id: 210, category_id: 3,  image: 'images/210.png', answer: 'とらくたー' )